### ISSUE TITLE
Plugin doesn't work on my ST3

### ISSUE THREAD

**Issue by Signoo** [Azd325/sublime-text-caniuse#12]
I've installed the plugin, restarted Sublime Text 3 and I could find the "Can I Use...." option by right clicking with the mouse, but when I click the option nothing happens.. How can I possibly fix this?

**Comment by Azd325** [comment]
Did you was in file where the syntax is set to css?  The right click is only by the css syntax.

**Comment by Azd325** [comment]
https://github.com/Azd325/sublime-text-caniuse/blob/master/useIt.py#L34

**Comment by Signoo** [comment]
@Azd325 I've tried on a CSS file with syntax set to CSS and both the right click and the shortcut (that I've added { "keys": ["command+shift+o"], "command": "use_it" } ) doesn't work

**Comment by Azd325** [comment]
I see you found a bug. :) 
You can fix it in the moment if you set explicit in the "can i use" settings the default browser. You can find them under the package settings in the menubar. 

```
{
    "default_browser": ""

	// Type Name	Class Name	Notes
	// 'mozilla'	Mozilla('mozilla')	 
	// 'firefox'	Mozilla('mozilla')	 
	// 'netscape'	Mozilla('netscape')	 
	// 'galeon'	Galeon('galeon')	 
	// 'epiphany'	Galeon('epiphany')	 
	// 'skipstone'	BackgroundBrowser('skipstone')	 
	// 'kfmclient'	Konqueror()	(1)
	// 'konqueror'	Konqueror()	(1)
	// 'kfm'	Konqueror()	(1)
	// 'mosaic'	BackgroundBrowser('mosaic')	 
	// 'opera'	Opera()	 
	// 'grail'	Grail()	 
	// 'links'	GenericBrowser('links')	 
	// 'elinks'	Elinks('elinks')	 
	// 'lynx'	GenericBrowser('lynx')	 
	// 'w3m'	GenericBrowser('w3m')	 
	// 'windows-default'	WindowsDefault	(2)
	// 'internet-config'	InternetConfig	(3)
	// 'macosx'	MacOSX('default')	(4)
	}

```

**Comment by Signoo** [comment]
@Azd325 Thanks for your help! Just a question, do I need to write instead of `"default_browser": ""` `"default_browser": "explicit"` or something else?

**Comment by Signoo** [comment]
@Azd325 Thank you very much! :) I've set the property to `"default_browser": "macosx"` and now it opens Chrome which is my default browser

**Comment by Azd325** [comment]
OK I will fix it later and document this setting.
