### ISSUE TITLE
can i use not working st2

### ISSUE THREAD

**Issue by ghost** [Azd325/sublime-text-caniuse#13]
st2 plugin only works single word, following selected

“overflow" will search and display
http://caniuse.com/#search=-webkit-overflow-scrolling

“scroll snap” or "scroll-snap” both 404 with
http://caniuse.com/%23search=Scroll%20snap%0Adiv%5Bid*=%2522c%2522%5D%20

however, search from within caniuse.com uri gives appropriate result
http://caniuse.com/#search=scroll%20snap
http://caniuse.com/#search=scroll-snap

**Comment by Azd325** [comment]
I tried it out and it works fine.
Please consider giving more information how I can produce your problem and reopen this ticket.
